### PR TITLE
Spanish translation added

### PR DESCRIPTION
**Pull request by jonathansamines**
Hi, i´d like to add my spanish translation for your excellent guide.

### CODE REVIEW

**Comment by juthilo** [comment]
This looks great, thank you so much for doing the translation!

Could you fix this typo: `encodign: UTF-8` -> `encoding: UTF-8` at the end of the guide and then squash your commits into a single one, please?

Thanks again, great work!

**Comment by jonathansamines** [comment]
I´m lost with squashing all commits in a single one. I did all changes on master branch and didnt know how to do this. Can you give me a hand?

Thanks!

**Comment by juthilo** [comment]
No problem at all! I'll dig in later today.

**Comment by jonathansamines** [comment]
Finally, i squashed all commits in a single one by doing this:

```
git rebase -i HEAD~no_commits
```

**Comment by juthilo** [comment]
Looks great, thanks again! I'll add a translation link section to the main guide shortly.

**Comment by jonathansamines** [comment]
Hi @juthilo seems you will not be accepting translations, looks like is more dificult to mantein this guide with the addition to github pages, however i updated my spanish translation to reflect the newest changes, should i restructuring my repository as a new guide with its own github page, and mantain it as a separated project? or what do you recommend i should do?

**Comment by juthilo** [comment]
@jnsamines Hi, great to hear that you've updated the translation! I will indeed no longer add translations to this repo, but I plan on adding some sort of translation list to the site.

It'd be great if you could host the translation yourself and I'd be happy to add a link to the English version once it's live.

You don't even need your own domain - have a look at GitHub's Help site if you're not familiar with using GitHub Pages.

Thanks for your work!

**Pull request merged**
